version: '2'
services:

  dask-worker:
    image: drtools/dask:latest
    command: dask-worker dask-scheduler:8786
    volumes:
      - ./data_root:/usr/share/data/
    depends_on:
      - dask-scheduler

  dask-scheduler:
    image: drtools/dask:latest
    command: dask-scheduler
    volumes:
      - ./data_root:/usr/share/data/
    ports:
      - "8787:8787"
      - "8786:8786"

  luigid:
    image: code-challenge/orchestrator:0.180
    build:
      context: ./orchestrator
    command: luigid
    ports:
      - "8082:8082"

  orchestrator:
    image: code-challenge/orchestrator:0.180
    depends_on:
      - luigid
      - dask-scheduler
    environment:
      - PROJECT_ROOT=/home/kamil/projects/code-challenge-2019
      - PIPELINE_VERSION=0.180
      - PYTHONPATH=/opt/orchestrator/
    volumes:
      - ./data_root:/usr/share/data/ # Mount data directory
      - /var/run/docker.sock:/var/run/docker.sock # Mount docker socker
    build:
      context: ./orchestrator
    command: luigi --module task Evaluate --scheduler-host luigid
