version: '2'
services:
  luigid:
    image: endpoint-blog-pipeline/orchestrator:latest
    build:
      context: ./orchestrator
    command: luigid
    ports:
      - "8082:8082"

  minio:
    image: minio/minio:RELEASE.2019-04-23T23-50-36Z
    environment:
      - "MINIO_ACCESS_KEY=s3_access_key"
      - "MINIO_SECRET_KEY=s3_secret_key"
    volumes:
       - ./data:/data
       - ./minio-config:/root/.minio
    ports:
      - "9000:9000"

  notebooks:
    image: endpoint-blog-pipeline/notebooks:latest
    environment:
      - "S3_ACCESS_KEY=s3_access_key"
      - "S3_SECRET_KEY=s3_secret_key"
    volumes:
      - ./data:/usr/share/data/
      - ./notebooks:/notebooks
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: ./orchestrator
    ports:
      - "8001:8001"
    command: jupyter lab --notebook-dir=/notebooks --ip 0.0.0.0 --allow-root --port 8001

  orchestrator:
    image: endpoint-blog-pipeline/orchestrator:latest
    depends_on:
      - luigid
    environment:
      - PROJECT_ROOT=/home/kamil/projects/endpoint-blog-nlp
      - PIPELINE_VERSION=latest
      - PYTHONPATH=/opt/orchestrator/
      - "S3_ACCESS_KEY=s3_access_key"
      - "S3_SECRET_KEY=s3_secret_key"
    volumes:
      - ./data:/usr/share/data/
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: ./orchestrator
    command: luigi --module task Evaluate --scheduler-host luigid
