apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: endpoint-blog-pipeline-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: base:5000/blog_pipeline_notebooks
      command: [python]
      args: ["--version"]
      resources:
        limits:
          memory: 32Mi
          cpu: 100m
