apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: endpoint-blog-pipeline-
spec:
  entrypoint: article-vectors
  volumes:
  - name: endpoint-blog-src
    hostPath:
      path: /home/kamil/data/endpoint-blog-src
      type: Directory
  templates:
  - name: clone-repo
    container:
      image: base:5000/blog_pipeline_clone_repo
      command: [bash]
      args: ["/run.sh"]
      volumeMounts:
      - mountPath: /data
        name: endpoint-blog-src
  - name: preprocess
    container:
      image: base:5000/blog_pipeline_preprocess
      command: [python]
      args: ["run.py"]
      volumeMounts:
      - mountPath: /data
        name: endpoint-blog-src
  - name: build-model
    container:
      image: base:5000/blog_pipeline_build_model
      command: [python]
      args: ["run.py"]
      volumeMounts:
      - mountPath: /data
        name: endpoint-blog-src
  - name: article-vectors
    dag:
      tasks:
      - name: src
        template: clone-repo
      - name: dataframe
        template: preprocess
        dependencies: [src]
      - name: model
        template: build-model
        dependencies: [dataframe]
